'use client';

import { useState } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { MissionSchema } from '@/lib/validations';
import { createMissionAction } from '@/app/actions';
import { useRouter } from 'next/navigation';
import { X, Rocket, ListTodo, CheckCircle2, ChevronRight, ChevronLeft } from 'lucide-react';

// Define the schema for the wizard (omit fields generated by server)
const WizardSchema = MissionSchema.omit({ 
  id: true, 
  readinessScore: true, 
  messages: true, 
  artifacts: true, 
  activityLog: true, 
  failures: true, 
  memoryItems: true 
});

type WizardData = z.infer<typeof WizardSchema>;

export function MissionWizard({ onClose }: { onClose: () => void }) {
  const [step, setStep] = useState(1);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const router = useRouter();

  const { register, handleSubmit, formState: { errors }, control } = useForm<WizardData>({
    resolver: zodResolver(WizardSchema),
    defaultValues: {
      name: '',
      objective: '',
      status: 'Active',
      phases: [
        { id: 'p1', name: 'Context Scan', status: 'Active' },
        { id: 'p2', name: 'Research & Extraction', status: 'Pending' },
        { id: 'p3', name: 'Implementation', status: 'Pending' },
        { id: 'p4', name: 'QA & Delivery', status: 'Pending' }
      ],
      tasks: []
    }
  });
  const watchedPhases = useWatch({ control, name: 'phases' });
  const watchedName = useWatch({ control, name: 'name' });
  const watchedObjective = useWatch({ control, name: 'objective' });

  const onSubmit = async (data: WizardData) => {
    setIsSubmitting(true);
    try {
      const initialTasks = [
        { 
          id: 't1', 
          title: 'Initialize Workspace', 
          description: `Analyze objective: ${data.objective}`, 
          agentName: 'Supr', 
          agentIcon: 'psychology', 
          status: 'Active' as const 
        }
      ];
      
      const fullData = {
        ...data,
        readinessScore: 0,
        messages: [{ id: Date.now(), sender: 'Supr', text: `Project ${data.name} initialized. Roadmap locked.`, isUser: false }],
        tasks: initialTasks,
        activityLog: [],
        failures: [],
        memoryItems: []
      };

      const newProj = await createMissionAction(fullData as any);
      if (newProj) {
        router.push(`/mission-control?id=${newProj.id}`);
      } else {
        router.push('/mission-control');
      }
      onClose();
    } catch (error) {
      console.error('Failed to create project:', error);
    } finally {
      setIsSubmitting(false);
    }
  };

  const nextStep = () => setStep(s => s + 1);
  const prevStep = () => setStep(s => s - 1);

  return (
    <div className="fixed inset-0 bg-primary/20 backdrop-blur-sm z-[100] flex items-center justify-center p-4">
      <div className="bg-background neo-border neo-shadow-lg w-full max-w-2xl flex flex-col max-h-[90vh]">
        {/* Header */}
        <header className="p-6 border-b-4 border-primary flex justify-between items-center bg-primary text-on-primary">
          <div className="flex items-center gap-3">
            <Rocket className="w-8 h-8" />
            <h2 className="font-headline text-2xl font-black uppercase tracking-tight">Project Builder</h2>
          </div>
          <button onClick={onClose} className="hover:rotate-90 transition-transform">
            <X className="w-8 h-8" />
          </button>
        </header>

        {/* Steps Indicator */}
        <div className="flex border-b-4 border-primary bg-surface-container">
           {[
             { n: 1, label: 'Objective', icon: Rocket },
             { n: 2, label: 'Roadmap', icon: ListTodo },
             { n: 3, label: 'Review', icon: CheckCircle2 }
           ].map((s) => (
             <div 
               key={s.n}
               className={`flex-1 flex items-center justify-center py-3 gap-2 border-r-4 border-primary last:border-r-0 transition-colors ${
                 step === s.n ? 'bg-primary-container text-on-primary-container font-bold' : 'text-on-surface-variant/50'
               }`}
             >
               <s.icon className="w-4 h-4" />
               <span className="font-headline text-xs uppercase hidden sm:inline">{s.label}</span>
             </div>
           ))}
         </div>

         {/* Form Content */}
         <form onSubmit={handleSubmit(onSubmit)} className="flex-1 overflow-y-auto p-8 space-y-8">
           
           {step === 1 && (
             <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
               <div className="space-y-2">
                 <label className="font-headline font-bold uppercase text-sm tracking-widest text-primary">Project Name</label>
                 <input 
                   {...register('name')}
                   placeholder="e.g. PROJECT_OMEGA"
                   className="w-full bg-background neo-border p-4 font-headline text-xl focus:ring-0 focus:border-tertiary uppercase"
                 />
                 {errors.name && <p className="text-error font-bold text-xs uppercase">{errors.name.message}</p>}
               </div>
               <div className="space-y-2">
                 <label className="font-headline font-bold uppercase text-sm tracking-widest text-primary">Core Objective</label>
                 <textarea 
                   {...register('objective')}
                   placeholder="Describe the end goal in detail..."
                   rows={4}
                   className="w-full bg-background neo-border p-4 font-body text-lg focus:ring-0 focus:border-tertiary"
                 />
                 {errors.objective && <p className="text-error font-bold text-xs uppercase">{errors.objective.message}</p>}
               </div>
             </div>
           )}

           {step === 2 && (
             <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300">
               <div className="bg-surface-container p-4 neo-border border-dashed">
                 <p className="font-body text-sm text-on-surface-variant italic">The Roadmap is automatically generated based on the Supr Standard. You can customize phases later in the Workspace.</p>
               </div>
               <div className="space-y-4">
                 {watchedPhases?.map((phase, idx) => (
                   <div key={phase.id || idx} className="flex items-center gap-4 bg-background neo-border p-4">
                     <div className="w-8 h-8 rounded-full bg-primary text-on-primary flex items-center justify-center font-bold text-xs">{idx + 1}</div>
                     <input 
                       {...register(`phases.${idx}.name`)}
                       className="flex-1 bg-transparent border-none p-0 font-headline font-bold uppercase focus:ring-0"
                     />
                   </div>
                 ))}
               </div>
             </div>
           )}

           {step === 3 && (
             <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-300 text-center">
               <div className="w-24 h-24 bg-tertiary-container text-tertiary rounded-full mx-auto flex items-center justify-center neo-border">
                 <Rocket className="w-12 h-12" />
               </div>
               <div>
                 <h3 className="font-headline text-3xl font-black uppercase tracking-tighter text-primary">{watchedName || 'Unnamed Project'}</h3>
                 <p className="font-body text-on-surface-variant mt-2 max-w-md mx-auto">{watchedObjective || 'No objective defined yet.'}</p>
               </div>
               <div className="bg-surface-container p-6 neo-border text-left">
                  <h4 className="font-headline font-bold uppercase text-xs mb-4 border-b-2 border-primary pb-1">Project Parameters</h4>
                  <ul className="space-y-2 font-body text-sm">
                     <li className="flex justify-between"><span>Status:</span> <span className="font-bold uppercase text-tertiary">Active Initialization</span></li>
                     <li className="flex justify-between"><span>Authority:</span> <span className="font-bold uppercase">Supervisor (Supr)</span></li>
                     <li className="flex justify-between"><span>Governance:</span> <span className="font-bold uppercase">Standard Protocol</span></li>
                  </ul>
               </div>
             </div>
           )}

         </form>

         {/* Footer */}
         <footer className="p-6 border-t-4 border-primary flex justify-between bg-surface">
           {step > 1 ? (
             <button 
               type="button"
               onClick={prevStep}
               className="flex items-center gap-2 font-headline font-bold uppercase hover:text-tertiary transition-colors"
             >
               <ChevronLeft className="w-5 h-5" /> Back
             </button>
           ) : <div />}

           {step < 3 ? (
             <button 
               type="button"
               onClick={nextStep}
               disabled={step === 1 && !watchedName}
               className="bg-primary text-on-primary neo-border px-8 py-3 font-headline font-bold uppercase hover:bg-tertiary transition-colors neo-shadow disabled:opacity-50 flex items-center gap-2"
             >
               Next <ChevronRight className="w-5 h-5" />
             </button>
           ) : (
             <button 
               type="submit"
               onClick={handleSubmit(onSubmit)}
               disabled={isSubmitting}
               className="bg-tertiary text-on-tertiary neo-border px-10 py-4 font-headline font-black uppercase hover:bg-primary transition-all neo-shadow active:translate-x-1 active:translate-y-1 disabled:opacity-50 flex items-center gap-3"
             >
               {isSubmitting ? 'Initializing...' : 'Create Project'}
               <Rocket className="w-6 h-6" />
             </button>
           )}
         </footer>
      </div>
    </div>
  );
}
