// scripts/append-loader.mjs
// Append loader functions to lib/agents.ts (handles CRLF endings)
import { readFileSync, writeFileSync, appendFileSync } from 'node:fs';

const path = 'lib/agents.ts';
const src = readFileSync(path, 'utf-8');

if (src.includes('export function loadIdentityProfile(')) {
    console.log('SKIP: loadIdentityProfile already present');
    process.exit(0);
}

const nl = src.includes('\r\n') ? '\r\n' : '\n';
const sep = `${nl}${nl}`;

const block = [
    '/**',
    ' * Loaded identity profile. Same shape that `writeIdentityProfile`',
    ' * produces, but rebuilt from disk by `loadIdentityProfile`.',
    ' */',
    'export interface LoadedIdentityProfile extends AgentIdentityProfile {',
    '  bodyMarkdown: string;',
    '  loadedAt: string;',
    '  sourcePath: string;',
    '}',
    '',
    '/**',
    ' * Parse the YAML frontmatter + markdown body of an identity .md file.',
    ' * The runtime uses this to pull a real, persona-shaped system prompt',
    ' * for each sub-agent instead of the hard-coded boilerplate. The',
    ' * parser is intentionally minimal -- one key/value per line, no',
    ' * nested structures -- because the writer in this same file is the',
    ' * only producer and the format is internal.',
    ' */',
    'export function parseIdentityMarkdown(source: string, fallbackName: string): AgentIdentityProfile {',
    '  const profile: AgentIdentityProfile = {',
    '    name: fallbackName,',
    '    role: \'Generalist\',',
    '    permissionTier: \'Observe\',',
    '    type: \'temporary\',',
    '    systemPrompt: \'\',',
    '    tools: [],',
    '  };',
    '  if (!source) return profile;',
    '',
    '  const fmMatch = source.match(/^---\\n([\\s\\S]*?)\\n---\\n([\\s\\S]*)$/);',
    '  if (!fmMatch) {',
    '    return { ...profile, systemPrompt: source.trim() };',
    '  }',
    '  const [, fm, body] = fmMatch;',
    '  const fields: Record<string, string> = {};',
    '  for (const line of fm.split(\'\\n\')) {',
    '    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*):\\s*(.*)$/);',
    '    if (m) fields[m[1]] = m[2].trim();',
    '  }',
    '  if (fields.name) profile.name = fields.name;',
    '  if (fields.role) profile.role = fields.role;',
    '  if (fields.permission_tier) profile.permissionTier = fields.permission_tier;',
    '  if (fields.type) profile.type = fields.type;',
    '  if (fields.tools) {',
    '    try {',
    '      const parsed = JSON.parse(fields.tools.replace(/\'/g, \'"\'));',
    '      if (Array.isArray(parsed)) profile.tools = parsed.map((t) => String(t));',
    '    } catch {',
    '      profile.tools = [];',
    '    }',
    '  }',
    '',
    '  // The body is the system prompt: everything from `# Directives` to',
    '  // the next major section. Fall back to the full body if we can\'t',
    '  // isolate the directive block.',
    '  const directivesMatch = body.match(/# Directives\\n([\\s\\S]*?)(?:\\n# |$)/);',
    '  profile.systemPrompt = (directivesMatch ? directivesMatch[1] : body).trim();',
    '  return profile;',
    '}',
    '',
    '/**',
    ' * Read an identity .md from disk and return a `LoadedIdentityProfile`.',
    ' * Returns null if the file is missing, in which case the caller',
    ' * should fall back to the hard-coded Agent_Actions row persona.',
    ' */',
    'export function loadIdentityProfile(name: string): LoadedIdentityProfile | null {',
    '  const filePath = getAgentFilePath(name);',
    '  if (!fs.existsSync(filePath)) return null;',
    '  const raw = fs.readFileSync(filePath, \'utf-8\');',
    '  const profile = parseIdentityMarkdown(raw, name);',
    '  return {',
    '    ...profile,',
    '    bodyMarkdown: raw,',
    '    loadedAt: new Date().toISOString(),',
    '    sourcePath: filePath,',
    '  };',
    '}',
    '',
    '/**',
    ' * Bulk loader: returns the loaded identity profile for every .md in',
    ' * `.agents/`. Used by the context assembler at session start so the',
    ' * runtime has a single map of (agent name) -> persona.',
    ' */',
    'export function loadAllIdentityProfiles(): Record<string, LoadedIdentityProfile> {',
    '  ensureAgentsDir();',
    '  const out: Record<string, LoadedIdentityProfile> = {};',
    '  for (const file of fs.readdirSync(AGENTS_DIR)) {',
    '    if (!file.endsWith(\'.md\')) continue;',
    '    const raw = fs.readFileSync(path.join(AGENTS_DIR, file), \'utf-8\');',
    '    const baseName = file.replace(/\\.md$/, \'\');',
    '    const profile = parseIdentityMarkdown(raw, baseName);',
    '    out[profile.name] = {',
    '      ...profile,',
    '      bodyMarkdown: raw,',
    '      loadedAt: new Date().toISOString(),',
    '      sourcePath: path.join(AGENTS_DIR, file),',
    '    };',
    '  }',
    '  return out;',
    '}',
    '',
].join(nl);

appendFileSync(path, sep + block + nl, 'utf-8');
console.log('OK: lib/agents.ts loader appended');
